#!/share/apps/virtualenv/pmgdb/bin/python
# EASY-INSTALL-SCRIPT: 'pymatgen-db==0.3.4','mgvv'
__requires__ = 'pymatgen-db==0.3.4'
import pkg_resources
pkg_resources.run_script('pymatgen-db==0.3.4', 'mgvv')
